# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Select one of:
# - profile_mc_1_21_2_to_1_21_4
# - profile_mc_1_21_5
# - profile_mc_1_21_6_to_1_21_8
# - profile_mc_1_21_9_to_1_21_10
# - profile_mc_1_21_11
buildProfile=profile_mc_1_21_2_to_1_21_4

# Mod Properties
mod_version=1.3.0
maven_group=com.ratger
archives_base_name=spyfilter
